language: python
matrix:
  include:
    - os: linux
      dist: trusty
      python: 3.5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
        env:
          - CXX=g++-5
    - os: linux
      dist: trusty
      python: 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
        env:
          - CXX=g++-5
    - os: linux
      dist: trusty
      python: 3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
        env:
          - CXX=g++-5
    - os: osx
      osx_image: xcode10.2
      language: shell
    - os: osx
      osx_image: xcode9.4
      language: shell
before_install:
- PYTHON_MAJOR_VERSION=`echo $TRAVIS_PYTHON_VERSION | head -c 1`
- pip3 install scikit-build
install:
- virtualenv -p python3 venv
- source venv/bin/activate
- python3 setup.py develop
script:
- python3 -m pytest -v -x tests.py

