language: python
python:
- '3.5'
- '3.6'
- '3.7-dev'
os: 
  - linux
    dist: trusty
    addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-5
    env:
      - CXX=g++-5
  - osx
    osx_image: xcode10.2
  - osx
    osx_image: xcode9.4
before_install:
- PYTHON_MAJOR_VERSION=`echo $TRAVIS_PYTHON_VERSION | head -c 1`
- sudo apt-get install python3-pip
- pip install scikit-build
install:
- virtualenv -p python3 venv
- source venv/bin/activate
- python setup.py develop
- python setup.py sdist
- python3 setup.py sdist bdist_wheel --universal
script:
- python3 -m pytest -v -x tests.py

